# Generated by Django 4.2 on 2023-05-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('roomType', models.CharField(choices=[('Deluxe room', 'Deluxe room'), ('Standard room', 'Standard room'), ('Suite', 'Suite'), ('Family room', 'Family room')], max_length=50)),
                ('checkInDate', models.DateField()),
                ('CheckOutDate', models.DateField()),
            ],
        ),
    ]
