# Generated by Django 4.2 on 2023-05-22 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_hotel_app', '0003_rename_fname_reservations_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='name',
            new_name='fname',
        ),
    ]
